# -------------------------------------
# Plan It
# Web Service
# 'configuration.py'
# Contact: planit.app.dev@gmail.com
# -------------------------------------

# Configuration onstants
SERVER_IP = '0.0.0.0'
SERVER_PORT = 5000
SECRET_KEY = 'SECRET_KEY'
SESSION_TYPE = 'SESSION_TYPE'
MONGO_DB = 'mongodb'
SESSION_MONGODB = 'SESSION_MONGODB'
SESSION_MONGODB_DB = 'SESSION_MONGODB_DB'
SESSION_MONGODB_COLLECT = 'SESSION_MONGODB_COLLECT'
PERMANENT_SESSION_LIFETIME = 'PERMANENT_SESSION_LIFETIME'
SESSION_USE_SIGNER = 'SESSION_USE_SIGNER'
SESSION_USE_SIGNER_VALUE = True
DB_CONNECTION_URI = 'DB_CONNECTION_URI'
DB_NAME = 'DB_NAME'
DB_SESSIONS_COLLECTION = 'sessions'
DB_USERS_COLLECTION = 'users'
DB_LISTS_COLLECTION = 'lists'
DB_PLACES_COLLECTION = 'places'